version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: login_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=login_db
      - DB_USER=demo_user
      - DB_PASSWORD=demo_pass
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  db_data:
